services:

  app:
    build: 
      context: ./new_backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:                         
    - ./new_backend/templates:/app/templates
    - ./new_backend/static:/app/static
    networks:
      - app_network
    restart: unless-stopped

  ollama:
    build:
      context: ./new_backend/
      dockerfile: Dockerfile.ollama
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
  ssl-certs:

networks:
  app_network:
    driver: bridge

