services:

  app:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:                         
    - ./backend/templates:/app/templates
    - ./backend/static:/app/static
    networks:
      - app_network
    restart: unless-stopped

  # ollama:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile.ollama
  #   networks:
  #     - app_network
  #   restart: unless-stopped
  #   volumes:
  #     - ollama_data:/root/.ollama

  ollama:
      build:
        context: ./backend/
        dockerfile: Dockerfile.ollama
      networks:
        - app_network
      restart: unless-stopped
      volumes:
        - ollama_data:/root/.ollama
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all  
                capabilities: [gpu]
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  postgres_data:
  ollama_data:
  ssl-certs:

networks:
  app_network:
    driver: bridge

