use_default_settings: true

server:
  secret_key: "change-this-to-any-random-string"
  limiter: false  
  image_proxy: true

search:
  safe_search: 0
  formats:
    - html
    - json

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
