basePath: /
definitions:
  models.ChatRequest:
    properties:
      history:
        items:
          $ref: '#/definitions/models.Message'
        type: array
      message:
        example: can you talk a little bit about my grandfather story?
        type: string
      model:
        type: string
    type: object
  models.Message:
    properties:
      content:
        type: string
      role:
        type: string
    type: object
  models.RagData:
    properties:
      content:
        example: Every family has that one recipe...
        type: string
      content_name:
        type: string
      embedding:
        items:
          type: number
        type: array
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@yourwebsite.com
    name: API Support
    url: http://www.yourwebsite.com/support
  description: Self hosted AI platform
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Farol IA
  version: "1.0"
paths:
  /api/chat:
    post:
      consumes:
      - application/json
      parameters:
      - description: Chat message
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Chat response
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send a message to the chat
      tags:
      - Chat
  /api/chat/rag:
    post:
      consumes:
      - application/json
      parameters:
      - description: Chat message
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: RAG chat response
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send a message using RAG context
      tags:
      - Chat
  /api/chat/web-search:
    post:
      consumes:
      - application/json
      parameters:
      - description: Chat message
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Web search chat response
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send a message with web search context
      tags:
      - Chat
  /api/rag:
    post:
      consumes:
      - application/json
      parameters:
      - description: Rag content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RagData'
      produces:
      - application/json
      responses:
        "201":
          description: Created successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new RAG data entry
      tags:
      - Rag
  /api/rag/get_all_data:
    get:
      consumes:
      - application/json
      responses:
        "201":
          description: Database data
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all data registered on the database
      tags:
      - Rag
  /api/rag/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Similar data found
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search for similar RAG data
      tags:
      - Rag
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
